<a href="https://colab.research.google.com/github/keenalise/Deep-learning-With-Tensor-Flow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#fundamental concept of tensors using TensorFlow
* introduction to tensors
* getting information from tensors
* manipulating tensors
* Tensors & NumPy
* Using @tf.function ( a way to speed up your regular Python functions )
* Using GPU with TensorFlow (or TPU)



## Introduction to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [3]:
# Create tensors using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim represents the number of dimensions)
scalar.ndim

0

In [5]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# check the dimension of our vector
vector.ndim

1

In [9]:
# create a matrix (it has more than one dimension)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
#check the dimension of this matrix
matrix.ndim

2

In [15]:
#create another matrix
another_matrix=tf.constant([[10., 7.],
                            [3., 2.],
                            [8., 9.]], dtype=tf.float16) #specify the datatype with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [16]:
# what's the number of dimension of another_matrix
another_matrix.ndim

2

In [17]:
#creating a tensor
tensor= tf.constant([[[1,2,3,],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [18]:
tensor.ndim

3